  {
  #out<-setwd('C:/Users/Cocha/Desktop/output-cbba/out')
  source("C:/Users/Cocha/Desktop/INFO/aeropuerto P. Cajon (Aut)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Aguadas Misicuni/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Aiquile Automática/15min.r")
  source("C:/Users/Cocha/Desktop/INFO/Alalay (Automatica)/15min.r")
  source("C:/Users/Cocha/Desktop/INFO/Calientes Automática/15min.r")
  source("C:/Users/Cocha/Desktop/INFO/Chiaraje Automática/15min.r")
  source("C:/Users/Cocha/Desktop/INFO/Chimboco (Aut)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Chiñata (Autom)/15min.r")
  source("C:/Users/Cocha/Desktop/INFO/Cuatro Esquinas Misicuni/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/El Abra (Autom)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/INAC Aeropuerto Cbba/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Lahuachama Presa (Aut.)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Linkupata (Automatica)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Misicuni (Automatica)/15min.r", encoding = 'UTF-8')#fdfdfd
  source("C:/Users/Cocha/Desktop/INFO/Mizque (Automática)/15min.r")
  source("C:/Users/Cocha/Desktop/INFO/Parque Tunari SDC (Autom)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Pasorapa (Automatica)/15min.r", encoding = 'UTF-8')  
  source("C:/Users/Cocha/Desktop/INFO/Pico de Loro (Autom)/15min.r", encoding = 'UTF-8')
  #source("C:/Users/Cocha/Desktop/INFO/PUENTE POJO 2022/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Pocona (Automatica)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Pojo (Automática)/15min.r")
  source("C:/Users/Cocha/Desktop/INFO/Presa Misicuni Aut/5min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Presa Totora Qhocha Aut/15min.r", encoding = 'UTF-8')  
  source("C:/Users/Cocha/Desktop/INFO/Puente Décima Aut. Hidr/15min.r")
  #sou  rce("C:/Users/Cocha/Desktop/INFO/Puente Pojo (Autom.)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Puente Siles (Hidro)/15min.r")
  source("C:/Users/Cocha/Desktop/INFO/Puerto Villarroel (Automatica)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Sacabamba/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/San Benito (Autom)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Sauce Pilapata (Autom.)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Senda VI (Automatica)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Sipe Sipe (Automática)/15min.r")
  source("C:/Users/Cocha/Desktop/INFO/Sunjani Misicuni/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Tapacari (Automática)/15min.r")
  source("C:/Users/Cocha/Desktop/INFO/Templo Misicuni/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Tiraque (Automatica)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Vacas (Automática)/15min.r")
  source("C:/Users/Cocha/Desktop/INFO/Vila Vila (Automatica)/15min.r", encoding = 'UTF-8')
  source("C:/Users/Cocha/Desktop/INFO/Viloma (Automatica)/15min.r", encoding = 'UTF-8')
  #a<-openxlsx::read.xlsx('C:/Users/Cocha/Desktop/Nihel/2023/senamhi-cbba_estaciones/Sarco.xlsx',detectDates = T)
  #a$date<-gsub('/','-',a$date)
  #date<-as.Date(paste(substr(a$date,7,10),substr(a$date,4,5),substr(a$date,1,2),sep='-'))
  #a$date<-a$date
  #write.csv(a,'C:/Users/Cocha/Desktop/output-cbba/out/Sarco.csv',row.names = F)
  b<-openxlsx::read.xlsx('C:/Users/Cocha/Desktop/output-cbba/Univalle Automática.xlsx',detectDates = T)
  #b$date<-seq(as.Date('2022-04-22'),as.Date('2023-01-15'),1)
  b$prcp<-round(b$prcp*100,1)
  b$tx<-round(b$tx,1);b$tn<-round(b$tn,1);b$HRmean<-round(b$HRmean,1);
  b$HRmax<-round(b$HRmax,1);b$HRmin<-round(b$HRmin,1)
  write.csv(b,'C:/Users/Cocha/Desktop/output-cbba/out/Univalle Automática.csv',row.names = F)
  source('C:/Users/Cocha/Desktop/Nihel/2023/tiempo_cbba.r')
  }

